### PR TITLE
change USB vendor string to tinysa.org, add USB product string for Ultra

### PR DESCRIPTION
**Pull request by Ho-Ro**
One minor addition to my previous PR:
Replace vendor string "STMicroelectronics" from demo code with "tinysa.org"
Use either "tinySA" or "tinySA Ultra" as product string depending on "#ifdef TINYSA4"

Signed-off-by: Martin <Ho-Ro@users.noreply.github.com>

EDIT: added a 2nd commit that displays the FW version as USB product sernum string, changed the USB product string for Ultra to "tinySA4" as also defined in Makefile and full FW version string, see dmesg log:

[  +1,567891] usb 1-1: new full-speed USB device number 121 using uhci_hcd
[  +0,179094] usb 1-1: New USB device found, idVendor=0483, idProduct=5740, bcdDevice= 2.00
[  +0,000008] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0,000005] usb 1-1: Product: tinySA
[  +0,000005] usb 1-1: Manufacturer: tinysa.org
[  +0,000004] usb 1-1: SerialNumber: v1.3-498-gf04006f
[  +0,003544] cdc_acm 1-1:1.0: ttyACM0: USB ACM device

### CODE REVIEW

**Comment by Ho-Ro** [comment]
@erikkaashoek 
Please hold your horses, the version string preparation fails for VERSION == 1.n without the -nnn-gxxxxxxx tail. I have to rethink, either I'll add another commit or close and redo it with a new all-in-one commit.
Sorry, Martin

EDIT: I found a solution that solves also a minor formatting issue, see below:

1. Changing the Makefile line to 
```Makefile
VERSION="$(PROJECT)_$(shell git describe --tags --long)"
```
shows the VERSION always as `<tag>-<number of commits>-g<hash>`, e.g. 
```
git describe --tags --long v1.2
v1.2-0-gc3e9c8a
```
2. The original formatting in `ui_sa.c` shows the versions on the left border of the LCD as
`1.2-3-g...` becomes `1.2-3-`,
`1.2-34-g...` becomes `1.2-34`
only the three-digit generation like `v1.2-345-g...` is formatted as expected as `1.2345`
`1.2-3456-g...` becomes `1.2-34` again :) (if you do so many commits without an up-version)
This is also be solved in my latest commit to `ui_sa.c` in this PR.

https://github.com/erikkaashoek/tinySA/blob/6ba8b027b949499c0e84ed7dfeefef2cd96f3cfd/ui_sa.c#L4387-L4400

**Comment by Ho-Ro** [comment]
@erikkaashoek What did my usbcfg.c hack destroy? I tested without issue on my Linux box.

**Comment by erikkaashoek** [comment]
I'm using an older C compiler that does not allow initialization of const
array with "test"[1]
Erik

**Comment by Ho-Ro** [comment]
Erik,
My bad - didn't check with an older compiler.
I use `gcc version 8.3.1 20190703 (release) [gcc-8-branch revision 273027] (15:8-2019-q3-1+b1)` directly available from debian stable.
Didn't check with the compiler version `gcc version 8.2.1 20181213 (release) [gcc-8-branch revision 267074] (GNU Tools for Arm Embedded Processors 8-2018-q4-major)` proposed in `README.md`.
Which tool chain do you use for your development?
Martin

**Comment by erikkaashoek** [comment]
I think gnu cc 7.2

Op di 15 nov. 2022 21:45 schreef Martin ***@***.***>:

**Comment by Ho-Ro** [comment]
Erik,
Yes, it's GCC 7.2.1, as seen on your latest release (do you use Windows / Mac / Linux?):
```
tinySA v0.3
2019-2022 Copyright @Erik Kaashoek
2016-2020 Copyright @edy555
SW licensed under GPL. See: https://github.com/erikkaashoek/tinySA
Version: tinySA_v1.3-501-gfbfd6d6
Build Time: Nov 15 2022 - 17:41:33
Kernel: 4.0.0
Compiler: GCC 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
Architecture: ARMv6-M Core Variant: Cortex-M0
Port Info: Preemption through NMI
Platform: STM32F072xB Entry Level Medium Density devices
``` 
I see also the reason for the 501 / 502 version mismatch discussed at [groups.io](https://groups.io/g/tinysa/message/7899):
The build was on Nov 15 2022 - 17:41:33, and the commit was later
```
commit be8defa7ef80551a86d12ba7d578a522070d2887 (HEAD -> V4.3, origin/V4.3, origin/HEAD)
Author: erikkaashoek <erik@kaashoek.com>
Date:   Tue Nov 15 17:55:50 2022 +0100
```
so the FW got the version info from the previous commit.
Martin

**Comment by erikkaashoek** [comment]
All on windows

Op di 15 nov. 2022 22:18 schreef Martin ***@***.***>:

**Comment by erikkaashoek** [comment]
I forgot to clean before the release build

Op di 15 nov. 2022 22:18 schreef Martin ***@***.***>:

**Comment by Ho-Ro** [comment]
Hi Erik,
I've updated my [Makefile](https://github.com/Ho-Ro/tinySA/blob/Ho-Ro_devel/Makefile), main targets are tinySA, tinySA4 and release, these targets buid all binaries either for one device, release builds for both. 
The binaries (bin, hex, dfu, elf) are copied into the main directory with their names changed to e.g.
`tinySA_v1.3-502-gbe8defa.bin`. With an unclean repo with uncommitted changes the version becomes `tinySA_v1.3-502-gbe8defa-dirty` (as well as the filenames).
Maybe it's useful for your release actions.
Martin

**Pull request merged**
